export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      fisheries: {
        Row: {
          id: string
          name: string
          slug: string
          description: string
          rules: string
          image: string
          species: string[]
          district: string
          isfeatured: boolean
          hasaccommodation: boolean
          created_at: string
          fishing_type: string[]
          facilities: string[]
          booking_type: string[]
          features: string[]
          pricing: string[]
          opening_times: string[]
          day_tickets: string[]
          payment: string[]
          website?: string
          contact_phone?: string
          contact_email?: string
          address?: string
          postcode?: string
          day_ticket_price?: number
          night_fishing_allowed?: boolean
          match_fishing_friendly?: boolean
          disabled_access?: boolean
          dog_friendly?: boolean
          price_range?: string
          fire_pits_allowed?: boolean
          parking_close?: boolean
          camping_allowed?: boolean
          catch_photos?: boolean
          wifi_signal?: string
          descriptionpage?: string
          fisheryimages1?: string
          fisheryimages2?: string
          fisheryimages3?: string
          fisheryvideo?: string
          bait_boats?: boolean
          magic_twig?: boolean
          tackle_shop?: boolean
          private_hire?: boolean
          tackle_hire?: boolean
          coaching?: boolean
          keepnets_allowed?: boolean
          tactics?: string
          fishery_of_the_week?: boolean
          record_biggest_fish?: string
          record_match_weight?: string
          stock?: string
          average_weight?: string
          access_all_hours?: boolean
          guests_allowed?: boolean
          under_18?: boolean
          latitude?: number
          longitude?: number
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description: string
          rules: string
          image: string
          species: string[]
          district: string
          isfeatured?: boolean
          hasaccommodation?: boolean
          created_at?: string
          fishing_type?: string[]
          facilities?: string[]
          booking_type?: string[]
          features?: string[]
          pricing?: string[]
          opening_times?: string[]
          day_tickets?: string[]
          payment?: string[]
          website?: string
          contact_phone?: string
          contact_email?: string
          address?: string
          postcode?: string
          day_ticket_price?: number
          night_fishing_allowed?: boolean
          match_fishing_friendly?: boolean
          disabled_access?: boolean
          dog_friendly?: boolean
          price_range?: string
          fire_pits_allowed?: boolean
          parking_close?: boolean
          camping_allowed?: boolean
          catch_photos?: boolean
          wifi_signal?: string
          descriptionpage?: string
          fisheryimages1?: string
          fisheryimages2?: string
          fisheryimages3?: string
          fisheryvideo?: string
          bait_boats?: boolean
          magic_twig?: boolean
          tackle_shop?: boolean
          private_hire?: boolean
          tackle_hire?: boolean
          coaching?: boolean
          keepnets_allowed?: boolean
          tactics?: string
          fishery_of_the_week?: boolean
          record_biggest_fish?: string
          record_match_weight?: string
          stock?: string
          average_weight?: string
          access_all_hours?: boolean
          guests_allowed?: boolean
          under_18?: boolean
          latitude?: number
          longitude?: number
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string
          rules?: string
          image?: string
          species?: string[]
          district?: string
          isfeatured?: boolean
          hasaccommodation?: boolean
          created_at?: string
          website?: string
          contact_phone?: string
          contact_email?: string
          address?: string
          postcode?: string
          day_ticket_price?: number
          fishing_type?: string[]
          facilities?: string[]
          booking_type?: string[]
          features?: string[]
          pricing?: string[]
          opening_times?: string[]
          day_tickets?: string[]
          payment?: string[]
          night_fishing_allowed?: boolean
          match_fishing_friendly?: boolean
          disabled_access?: boolean
          dog_friendly?: boolean
          price_range?: string
          fire_pits_allowed?: boolean
          parking_close?: boolean
          camping_allowed?: boolean
          catch_photos?: boolean
          wifi_signal?: string
          descriptionpage?: string
          fisheryimages1?: string
          fisheryimages2?: string
          fisheryimages3?: string
          fisheryvideo?: string
          bait_boats?: boolean
          magic_twig?: boolean
          tackle_shop?: boolean
          private_hire?: boolean
          tackle_hire?: boolean
          coaching?: boolean
          keepnets_allowed?: boolean
          tactics?: string
          fishery_of_the_week?: boolean
          record_biggest_fish?: string
          record_match_weight?: string
          stock?: string
          average_weight?: string
          access_all_hours?: boolean
          guests_allowed?: boolean
          under_18?: boolean
          latitude?: number
          longitude?: number
        }
      }
      lakes: {
        Row: {
          id: string
          fishery_id: string
          name: string
          description: string
          species: string[]
          size_acres?: number
          max_depth_ft?: number
          pegs?: number
          created_at: string
        }
        Insert: {
          id?: string
          fishery_id: string
          name: string
          description: string
          species: string[]
          size_acres?: number
          max_depth_ft?: number
          pegs?: number
          created_at?: string
        }
        Update: {
          id?: string
          fishery_id?: string
          name?: string
          description?: string
          species?: string[]
          size_acres?: number
          max_depth_ft?: number
          pegs?: number
          created_at?: string
        }
      }
      accommodation: {
        Row: {
          id: string
          fishery_id: string
          type: string
          price: number
          notes: string
          image?: string
          created_at: string
          featured?: boolean
        }
        Insert: {
          id?: string
          fishery_id: string
          type: string
          price: number
          notes: string
          image?: string
          created_at?: string
          featured?: boolean
        }
        Update: {
          id?: string
          fishery_id?: string
          type?: string
          price?: number
          notes?: string
          image?: string
          created_at?: string
          featured?: boolean
        }
      }
      messages: {
        Row: {
          id: string
          name: string
          email: string
          message: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          message: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          message?: string
          created_at?: string
        }
      }
      tackle_shops: {
        Row: {
          id: string
          name: string
          slug: string
          description: string
          image: string
          address: string
          postcode: string
          website?: string
          phone?: string
          email?: string
          opening_hours?: Json
          brands: string[]
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description: string
          image: string
          address: string
          postcode: string
          website?: string
          phone?: string
          email?: string
          opening_hours?: Json
          brands: string[]
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string
          image?: string
          address?: string
          postcode?: string
          website?: string
          phone?: string
          email?: string
          opening_hours?: Json
          brands?: string[]
          created_at?: string
        }
      }
    }
  }
}